/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package paintbasico2d;

import java.awt.BasicStroke;
import java.awt.Color;

/**
 *
 * @author curro
 */
public class MarcoSecundario extends javax.swing.JInternalFrame {

    private MarcoPrincipal ventana;
    
    /**
     * Creates new form MarcoSecundario
     */
    public MarcoSecundario() {
        initComponents();
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        
        ventana=new MarcoPrincipal();
    }

    public void setHerramienta(Herramientas h){
        lienzo1.setHerramienta(h);
    }
    
    public void setColor(Color c){
        lienzo1.setColor(c);
    }
    
    public void setGrosor(int i){
        lienzo1.setGrosor(new BasicStroke(i));
    }
    
    public void setRelleno(boolean relleno){
        lienzo1.setRelleno(relleno);
    }
    
    public boolean isRelleno(){
        return lienzo1.isRelleno();
    }

    public void setVentana(MarcoPrincipal ventana) {
        this.ventana=ventana;
    }

    public MarcoPrincipal getVentana() {
        return ventana;
    }
    
    public void setEditar(boolean editar){
        lienzo1.setEditar(editar);
    }
    
    public boolean isEditar(){
        return lienzo1.isEditar();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lienzo1 = new paintbasico2d.Lienzo();

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private paintbasico2d.Lienzo lienzo1;
    // End of variables declaration//GEN-END:variables
}
