package paintbasico2d;

import java.awt.BasicStroke;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JFileChooser;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;

/**
 *
 * @author Francisco Beltrán Sánchez
 */
public class MarcoPrincipal extends javax.swing.JFrame {

    /**
     * Atributos de la ventana principal
     */
    private MarcoSecundario ventanaActiva;
    private MiManejador manejador=new MiManejador();
    
    /**
     * Creates new form MarcoPrincipal
     */
    private ArrayList<MarcoSecundario> lienzos=new ArrayList();
   
    public MarcoPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraSuperior = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        modoPunto = new javax.swing.JToggleButton();
        modoLinea = new javax.swing.JToggleButton();
        modoRectangulo = new javax.swing.JToggleButton();
        modoElipse = new javax.swing.JToggleButton();
        jSeparator2 = new javax.swing.JSeparator();
        seleccionColores = new javax.swing.JComboBox<Color>();
        jSeparator3 = new javax.swing.JSeparator();
        selectorGrosor = new javax.swing.JSpinner();
        modoEditar = new javax.swing.JToggleButton();
        modoRelleno = new javax.swing.JToggleButton();
        modoTransparencia = new javax.swing.JToggleButton();
        modoAlisar = new javax.swing.JToggleButton();
        barraInferior = new javax.swing.JPanel();
        barraEstado = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();
        barraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        opcionNuevo = new javax.swing.JMenuItem();
        opcionAbrir = new javax.swing.JMenuItem();
        opcionGuardar = new javax.swing.JMenuItem();
        menuEdicion = new javax.swing.JMenu();
        visibilidadBarraEstado = new javax.swing.JMenuItem();
        visibilidadBarraFormas = new javax.swing.JMenuItem();
        visibilidadBarraAtributos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        barraSuperior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/iconos/nuevo.png"))); // NOI18N
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        barraSuperior.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/iconos/abrir.png"))); // NOI18N
        barraSuperior.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/iconos/guardar.png"))); // NOI18N
        barraSuperior.add(jButton3);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(2, 50));
        barraSuperior.add(jSeparator1);

        modoPunto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/iconos/punto.png"))); // NOI18N
        modoPunto.setFocusable(false);
        modoPunto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modoPunto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modoPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoPuntoActionPerformed(evt);
            }
        });
        barraSuperior.add(modoPunto);

        modoLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/iconos/linea.png"))); // NOI18N
        modoLinea.setFocusable(false);
        modoLinea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modoLinea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modoLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoLineaActionPerformed(evt);
            }
        });
        barraSuperior.add(modoLinea);

        modoRectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/iconos/rectangulo.png"))); // NOI18N
        modoRectangulo.setFocusable(false);
        modoRectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modoRectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modoRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoRectanguloActionPerformed(evt);
            }
        });
        barraSuperior.add(modoRectangulo);

        modoElipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/iconos/elipse.png"))); // NOI18N
        modoElipse.setFocusable(false);
        modoElipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modoElipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modoElipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoElipseActionPerformed(evt);
            }
        });
        barraSuperior.add(modoElipse);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setPreferredSize(new java.awt.Dimension(2, 50));
        barraSuperior.add(jSeparator2);

        seleccionColores.setRenderer(new MiCellRenderer());
        seleccionColores.setModel(new javax.swing.DefaultComboBoxModel(new Color[] { Color.BLACK, Color.RED, Color.BLUE, Color.WHITE, Color.YELLOW, Color.GREEN }));
        seleccionColores.setPreferredSize(new java.awt.Dimension(60, 40));
        seleccionColores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seleccionColoresItemStateChanged(evt);
            }
        });
        barraSuperior.add(seleccionColores);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(2, 50));
        barraSuperior.add(jSeparator3);

        selectorGrosor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                selectorGrosorStateChanged(evt);
            }
        });
        barraSuperior.add(selectorGrosor);

        modoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/iconos/seleccion.png"))); // NOI18N
        modoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoEditarActionPerformed(evt);
            }
        });
        barraSuperior.add(modoEditar);

        modoRelleno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/iconos/rellenar.png"))); // NOI18N
        modoRelleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoRellenoActionPerformed(evt);
            }
        });
        barraSuperior.add(modoRelleno);

        modoTransparencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/iconos/transparencia.png"))); // NOI18N
        modoTransparencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoTransparenciaActionPerformed(evt);
            }
        });
        barraSuperior.add(modoTransparencia);

        modoAlisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/iconos/alisar.png"))); // NOI18N
        modoAlisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoAlisarActionPerformed(evt);
            }
        });
        barraSuperior.add(modoAlisar);

        getContentPane().add(barraSuperior, java.awt.BorderLayout.PAGE_START);

        barraInferior.setLayout(new java.awt.BorderLayout());

        barraEstado.setText("Hola");
        barraEstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        barraInferior.add(barraEstado, java.awt.BorderLayout.SOUTH);

        getContentPane().add(barraInferior, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(escritorio, java.awt.BorderLayout.CENTER);

        menuArchivo.setText("Archivo");

        opcionNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/iconos/nuevo.png"))); // NOI18N
        opcionNuevo.setText("Nuevo");
        opcionNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionNuevoActionPerformed(evt);
            }
        });
        menuArchivo.add(opcionNuevo);

        opcionAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/iconos/abrir.png"))); // NOI18N
        opcionAbrir.setText("Abrir");
        opcionAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionAbrirActionPerformed(evt);
            }
        });
        menuArchivo.add(opcionAbrir);

        opcionGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintbasico2d/iconos/guardar.png"))); // NOI18N
        opcionGuardar.setText("Guardar");
        opcionGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionGuardarActionPerformed(evt);
            }
        });
        menuArchivo.add(opcionGuardar);

        barraMenu.add(menuArchivo);

        menuEdicion.setText("Edición");

        visibilidadBarraEstado.setText("Ver barra de estado");
        visibilidadBarraEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visibilidadBarraEstadoActionPerformed(evt);
            }
        });
        menuEdicion.add(visibilidadBarraEstado);

        visibilidadBarraFormas.setText("Ver barra de formas");
        visibilidadBarraFormas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visibilidadBarraFormasActionPerformed(evt);
            }
        });
        menuEdicion.add(visibilidadBarraFormas);

        visibilidadBarraAtributos.setText("Ver barra de atributos");
        visibilidadBarraAtributos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visibilidadBarraAtributosActionPerformed(evt);
            }
        });
        menuEdicion.add(visibilidadBarraAtributos);

        barraMenu.add(menuEdicion);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Para limpiar la pantalla generamos un punto en una posición del lienzo
     * que no sea visible, y la establecemos como punto inicial y final de una 
     * figura.
    */
    private void opcionNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionNuevoActionPerformed
        lienzos.add(new MarcoSecundario());
        escritorio.add(lienzos.get(lienzos.size()-1));
        lienzos.get(lienzos.size()-1).setVisible(true);
        
        ventanaActiva=lienzos.get(lienzos.size()-1);
        ventanaActiva.addInternalFrameListener(manejador);
        
        cambiarEstadoHerramientas(ventanaActiva.getHerramienta());
        cambiarEstadoPropiedades(ventanaActiva.getLienzo().isEditar(),
                                    ventanaActiva.getLienzo().isAlisado(),
                                    ventanaActiva.getLienzo().isTransparencia(),
                                    ventanaActiva.getLienzo().isRelleno());

        seleccionarColor((Color)ventanaActiva.getLienzo().getColor());
    }//GEN-LAST:event_opcionNuevoActionPerformed

    /**
     * Acciones realizadas al seleccionar en la barra de herramientas el modo
     * punto. A parte de modificar el atributo herramienta de la clase lienzo,
     * se modifica el atributo de selección de los botones de herramientas, evitando que esten 
     * dos o más seleccionados, o que si se pulsa dos veces el mismo no se 
     * deseleccione el botón de la herramienta actual, indicando de manera clara
     * cual es la forma de dibujo seleccionada.
     *
     * @param evt 
     */
    private void modoPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoPuntoActionPerformed
        obtenerVentanaActiva();
        
        if(ventanaActiva!=null){
            ventanaActiva.setHerramienta(Herramientas.Punto);
            cambiarEstadoHerramientas(ventanaActiva.getHerramienta());
        }
            
    }//GEN-LAST:event_modoPuntoActionPerformed

    /**
     * Acciones realizadas al seleccionar en la barra de herramientas el modo
     * línea. A parte de modificar el atributo herramienta de la clase lienzo,
     * se modifica el atributo de selección de los botones de herramientas, evitando que esten 
     * dos o más seleccionados, o que si se pulsa dos veces el mismo no se 
     * deseleccione el botón de la herramienta actual, indicando de manera clara
     * cual es la forma de dibujo seleccionada.
     * 
     * @param evt 
     */
    private void modoLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoLineaActionPerformed
        obtenerVentanaActiva();
        
        if(ventanaActiva!=null){
            ventanaActiva.setHerramienta(Herramientas.Linea);
            cambiarEstadoHerramientas(ventanaActiva.getHerramienta());
        }
        
    }//GEN-LAST:event_modoLineaActionPerformed

    /**
     * Acciones realizadas al seleccionar en la barra de herramientas el modo
     * rectángulo. A parte de modificar el atributo herramienta de la clase lienzo,
     * se modifica el atributo de selección de los botones de herramientas, evitando que esten 
     * dos o más seleccionados, o que si se pulsa dos veces el mismo no se 
     * deseleccione el botón de la herramienta actual, indicando de manera clara
     * cual es la forma de dibujo seleccionada.
     * 
     * @param evt 
     */
    private void modoRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoRectanguloActionPerformed
        obtenerVentanaActiva();
        
        if(ventanaActiva!=null){
            ventanaActiva.setHerramienta(Herramientas.Cuadrado);
            cambiarEstadoHerramientas(ventanaActiva.getHerramienta());
        }
    }//GEN-LAST:event_modoRectanguloActionPerformed

    /**
     * Acciones realizadas al seleccionar en la barra de herramientas el modo
     * elipse/óvalo. A parte de modificar el atributo herramienta de la clase lienzo,
     * se modifica el atributo de selección de los botones de herramientas, evitando que esten 
     * dos o más seleccionados, o que si se pulsa dos veces el mismo no se 
     * deseleccione el botón de la herramienta actual, indicando de manera clara
     * cual es la forma de dibujo seleccionada.
     * 
     * @param evt 
     */
    private void modoElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoElipseActionPerformed
        obtenerVentanaActiva();
        
        if(ventanaActiva!=null){
            ventanaActiva.setHerramienta(Herramientas.Ovalo);
            cambiarEstadoHerramientas(ventanaActiva.getHerramienta());
        }
    }//GEN-LAST:event_modoElipseActionPerformed

    /**
     * Accion realizada al seleccionar en el menu de edición la visibilidad de 
     * la barra de estado.
     * 
     * @param evt 
     */
    private void visibilidadBarraEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visibilidadBarraEstadoActionPerformed
        barraEstado.setVisible(!barraEstado.isVisible());
    }//GEN-LAST:event_visibilidadBarraEstadoActionPerformed

    /**
     * Accion realizada al seleccionar en el menu de archivo la opción abrir. No
     * se abre ningún archivo ya que no tendría sentido en el programa, solo se 
     * abre la ventana de diálogo correspondiente.
     * 
     * @param evt 
     */
    private void opcionAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionAbrirActionPerformed
        JFileChooser dlg=new JFileChooser();
        int resp=dlg.showOpenDialog(this);
        if(resp==JFileChooser.APPROVE_OPTION){
            File f =dlg.getSelectedFile();
        }
    }//GEN-LAST:event_opcionAbrirActionPerformed

    /**
     * Accion realizada al seleccionar en el menu de archivo la opción guardar. No
     * se guarda ningún archivo ya que no tendría sentido en el programa, solo se 
     * abre la ventana de diálogo correspondiente.
     * 
     * @param evt 
     */
    private void opcionGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionGuardarActionPerformed
        JFileChooser dlg=new JFileChooser();
        int resp=dlg.showSaveDialog(this);
        if(resp==JFileChooser.APPROVE_OPTION){
            File f =dlg.getSelectedFile();
        }
    }//GEN-LAST:event_opcionGuardarActionPerformed

    private void selectorGrosorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_selectorGrosorStateChanged
        obtenerVentanaActiva();
        
        if(ventanaActiva!=null)
            ventanaActiva.setGrosor((int)selectorGrosor.getValue());
    }//GEN-LAST:event_selectorGrosorStateChanged

    private void visibilidadBarraFormasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visibilidadBarraFormasActionPerformed
        modoPunto.setVisible(!modoPunto.isVisible());
        modoLinea.setVisible(!modoLinea.isVisible());
        modoRectangulo.setVisible(!modoRectangulo.isVisible());
        modoElipse.setVisible(!modoElipse.isVisible());

    }//GEN-LAST:event_visibilidadBarraFormasActionPerformed

    private void visibilidadBarraAtributosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visibilidadBarraAtributosActionPerformed
        modoEditar.setVisible(!modoEditar.isVisible());
        modoAlisar.setVisible(!modoAlisar.isVisible());
        modoRelleno.setVisible(!modoRelleno.isVisible());
        modoTransparencia.setVisible(!modoTransparencia.isVisible());
    }//GEN-LAST:event_visibilidadBarraAtributosActionPerformed

    private void seleccionColoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seleccionColoresItemStateChanged
        obtenerVentanaActiva();
        
        if(ventanaActiva!=null)
            ventanaActiva.setColor((Color)evt.getItem());
    }//GEN-LAST:event_seleccionColoresItemStateChanged

    private void modoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoEditarActionPerformed
        obtenerVentanaActiva();
        
        if(ventanaActiva!=null){
            ventanaActiva.setEditar(!ventanaActiva.isEditar());
            if(ventanaActiva.isEditar())
                barraEstado.setText("Modo editar activado");
            else
                barraEstado.setText("Modo editar desactivado");
        }
    }//GEN-LAST:event_modoEditarActionPerformed

    private void modoRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoRellenoActionPerformed
        obtenerVentanaActiva();
        
        if(ventanaActiva!=null){
            ventanaActiva.setRelleno(!ventanaActiva.isRelleno());
            if(ventanaActiva.isRelleno())
                barraEstado.setText("Relleno activado");
            else
                barraEstado.setText("Relleno desactivado");
        }
    }//GEN-LAST:event_modoRellenoActionPerformed

    private void modoTransparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoTransparenciaActionPerformed
        obtenerVentanaActiva();
        
        if(ventanaActiva!=null){
            ventanaActiva.setTransparencia(!ventanaActiva.isTransparencia());
            if(ventanaActiva.isTransparencia())
                barraEstado.setText("Modo transparencia activado");
            else
                barraEstado.setText("Modo transparencia desactivado");
        }
    }//GEN-LAST:event_modoTransparenciaActionPerformed

    private void modoAlisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoAlisarActionPerformed
        obtenerVentanaActiva();
        
        if(ventanaActiva!=null){
            ventanaActiva.setAlisado(!ventanaActiva.isAlisado());
            if(ventanaActiva.isAlisado())
                barraEstado.setText("Modo alisado activado");
            else
                barraEstado.setText("Modo alisado desactivado");
        }
    }//GEN-LAST:event_modoAlisarActionPerformed
   
    /**
     * Método para obtener cual de los marcos secundarios está activo. Si existe
     * algún cambio se cambian las propiedades de la ventana principal conforme
     * a lo que tenga almacenado la ventana secundaria
     */
    private void obtenerVentanaActiva(){    
        if(ventanaActiva!=null){
            ventanaActiva=(MarcoSecundario)escritorio.getSelectedFrame();
        }
    }
    
    /**
     * Clase manejadora de eventos del lienzo en MarcoPrincipal.
     */
    
    public class MiManejador extends InternalFrameAdapter{
        
        @Override
        public void internalFrameActivated(InternalFrameEvent evt){
            ventanaActiva=(MarcoSecundario)evt.getInternalFrame();
            
            cambiarEstadoHerramientas(ventanaActiva.getHerramienta());
            
            cambiarEstadoPropiedades(ventanaActiva.getLienzo().isEditar(),
                                     ventanaActiva.getLienzo().isAlisado(),
                                     ventanaActiva.getLienzo().isTransparencia(),
                                     ventanaActiva.getLienzo().isRelleno());
            
            seleccionarColor((Color)ventanaActiva.getLienzo().getColor());
            
            cambiarValorGrosor(ventanaActiva.getLienzo().getGrosor());
        }
    }
    
    public void cambiarEstadoHerramientas(Herramientas h){
        switch(h){
            case Punto:
                modoLinea.setSelected(false);
                modoRectangulo.setSelected(false);
                modoElipse.setSelected(false);
                modoPunto.setSelected(true);

                barraEstado.setText("Modo punto");
            break;

            case Linea:

                modoPunto.setSelected(false);
                modoRectangulo.setSelected(false);
                modoElipse.setSelected(false);
                modoLinea.setSelected(true);

                barraEstado.setText("Modo línea");

            break;

            case Cuadrado:

                modoPunto.setSelected(false);
                modoLinea.setSelected(false);
                modoElipse.setSelected(false);
                modoRectangulo.setSelected(true);

                barraEstado.setText("Modo rectángulo");

            break;

            case Ovalo:
                modoPunto.setSelected(false);
                modoLinea.setSelected(false);
                modoRectangulo.setSelected(false);
                modoElipse.setSelected(true);

                barraEstado.setText("Modo elipse");
            break;
        }
    }
    
    public void cambiarEstadoPropiedades(boolean e, boolean t, boolean a, boolean r){
        modoRelleno.setSelected(r);
        modoAlisar.setSelected(a);
        modoTransparencia.setSelected(t);
        modoEditar.setSelected(e);
        
    }

    public void seleccionarColor(Color c){
        this.seleccionColores.setSelectedItem((Color)c);
    }
    
    public void cambiarValorGrosor(BasicStroke i){
        selectorGrosor.setValue(i);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barraEstado;
    private javax.swing.JPanel barraInferior;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JPanel barraSuperior;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuEdicion;
    private javax.swing.JToggleButton modoAlisar;
    private javax.swing.JToggleButton modoEditar;
    private javax.swing.JToggleButton modoElipse;
    private javax.swing.JToggleButton modoLinea;
    private javax.swing.JToggleButton modoPunto;
    private javax.swing.JToggleButton modoRectangulo;
    private javax.swing.JToggleButton modoRelleno;
    private javax.swing.JToggleButton modoTransparencia;
    private javax.swing.JMenuItem opcionAbrir;
    private javax.swing.JMenuItem opcionGuardar;
    private javax.swing.JMenuItem opcionNuevo;
    private javax.swing.JComboBox<Color> seleccionColores;
    private javax.swing.JSpinner selectorGrosor;
    private javax.swing.JMenuItem visibilidadBarraAtributos;
    private javax.swing.JMenuItem visibilidadBarraEstado;
    private javax.swing.JMenuItem visibilidadBarraFormas;
    // End of variables declaration//GEN-END:variables
}
