/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Paint2D;

import java.awt.Dimension;

/**
 *
 * @author curro
 */
public class MiDialogo extends javax.swing.JDialog {

    /**
     * Creates new form MiDialogo
     * @param parent
     * @param modal
     * @param mensaje
     */
    public MiDialogo(java.awt.Frame parent, boolean modal, String mensaje) {
        super(parent, modal);
        initComponents();
        
        texto.setText(mensaje);
        
        this.setMinimumSize(new Dimension(texto.getWidth(),texto.getHeight()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        texto = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Error");
        setMinimumSize(new java.awt.Dimension(250, 100));
        setResizable(false);

        texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto.setText("jLabel1");
        texto.setMinimumSize(new java.awt.Dimension(150, 60));
        getContentPane().add(texto, java.awt.BorderLayout.CENTER);
        getContentPane().add(jSeparator2, java.awt.BorderLayout.LINE_START);
        getContentPane().add(jSeparator3, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
