/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practica14;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.image.BufferedImage;

/**
 *
 * @author curro
 */
public class VentanaInternaCamara extends javax.swing.JInternalFrame {
    private Webcam camara=null;
    /**
     * Creates new form VentanaInternaCamara
     */
    private VentanaInternaCamara() {
        initComponents();
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        camara=Webcam.getDefault(); //Obtenemos la primera camara disponible
        
        Dimension resoluciones[]=camara.getViewSizes();
        camara.setViewSize(resoluciones[resoluciones.length-1]); //Establecemos el video en maxima resolucion
        
        if(camara!=null){
            WebcamPanel areaVisual=new WebcamPanel(camara); //Creamos la pantalla donde se vera nuestra camara
            if(areaVisual!=null){
                getContentPane().add(areaVisual, BorderLayout.CENTER); //Situamos esta pantalla en el marco que hemos creado
                pack();
            }
        }
    }

    /**
     * Metodo que nos devuelve un objeto VentanaInternaCamara ya creado.
     * @return 
     */
    public static VentanaInternaCamara getInstance(){
        VentanaInternaCamara v=new VentanaInternaCamara();
        return(v.camara!=null?v:null);
    }
    
    public BufferedImage getImage(){
        return camara.getImage(); //Realiza una captura de la instantanea actual de la webcam
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Proceso a seguir al cerrar la ventana creada
     * @param evt 
     */
    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        camara.close();
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
