/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practica14;

import java.io.File;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.player.MediaPlayerEventListener;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;

/**
 *
 * @author curro
 */
public class VentanaInternaVideo extends javax.swing.JInternalFrame {

    private EmbeddedMediaPlayer vlcplayer=null; //Reproductor
    private File fMedia; //Archivo asociado
    
    /**
     * Creates new form VentanaInternaVideo
     */
    private VentanaInternaVideo(File f) {
        initComponents();
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setSize(300, 300);
        
        fMedia=f;
        EmbeddedMediaPlayerComponent aVisual=new EmbeddedMediaPlayerComponent(); //Creamos la pantalla de reproduccion
        getContentPane().add(aVisual,java.awt.BorderLayout.CENTER); //La posicionamos en la ventana contenedora
        
        vlcplayer=aVisual.getMediaPlayer(); //Obtenemos el objeto reproductor a partir de la pantalla de reproduccion asociada
    }
    /**
     * Metodo que nos devuelve un objeto VentanaInternaVideo ya creado.
     * @return 
     */
    public static VentanaInternaVideo getInstance(File f){
        VentanaInternaVideo v=new VentanaInternaVideo(f);
        return(v.vlcplayer!=null?v:null);
    }
    
    public void play(){
        if(vlcplayer!=null){
            if(vlcplayer.isPlayable()){ //Si el reproductor contiene un video reproducible se dispone a iniciarlo
                vlcplayer.play();
            }
            else{ //Si no, comienza la reproduccion del archivo asociado
                vlcplayer.playMedia(fMedia.getAbsolutePath()); 
            }
        }
    }
    
    public void stop(){
        if(vlcplayer!=null){
            if(vlcplayer.isPlaying()){ //Si el video se esta reproduciendo lo pausa
                vlcplayer.pause();
            }
            else{ //Si no, lo detiene por completo
                vlcplayer.stop();
            }
        }
    }
    
    //Asigna un manejador de eventos al reproductor.
    public void addMediaPlayerEventListener(MediaPlayerEventListener m1){
        if(vlcplayer!=null){
            vlcplayer.addMediaPlayerEventListener(m1);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Proceso a seguir al cerrar la ventana creada
     * @param evt 
     */
    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        vlcplayer.stop();
        vlcplayer=null;
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
